name: lafla
description: "A new Flutter project."
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '>=3.0.3 <4.0.0'
dependencies:
  bloc: ^8.1.3
  cached_network_image: ^3.3.1
  pin_code_fields: ^8.0.1
  cloud_firestore: ^4.14.0
  cupertino_icons: ^1.0.6
  firebase_auth: ^4.16.0
  firebase_core: ^2.11.0
  firebase_database: ^10.4.0
  firebase_messaging: ^14.7.10
  firebase_storage: ^11.6.0
  country_pickers: ^2.0.0
  smooth_page_indicator: ^1.1.0
  outline_gradient_button: ^2.0.1+1
  flutter:
    sdk: flutter
  flutter_bloc: ^8.1.4
  flutter_svg: ^1.1.6
  flutter_svg_provider: ^1.0.0
  google_sign_in: ^6.0.0
  http: ^0.13.6
  image_picker: ^1.0.7
  intl: ^0.18.0
  lottie: ^2.4.0
  shared_preferences: ^2.2.2

dev_dependencies:
  flutter:
    sdk: flutter
  flutter_launcher_icons: ^0.13.1
flutter_icons:
  android: true
  ios: true
  image_path: "assets/images/logo.png"
  flutter_lints: ^3.0.0
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true
  assets:
    - assets/
    - assets/images/
  fonts:
    - family: Plus Jakarta Sans
      fonts:
        - asset: assets/fonts/PlusJakartaSansRomanBold.ttf
          weight: 700
        - asset: assets/fonts/PlusJakartaSansRomanRegular.ttf
          weight: 400
        - asset: assets/fonts/PlusJakartaSansRomanSemiBold.ttf
          weight: 600
        - asset: assets/fonts/PlusJakartaSansRomanMedium.ttf
          weight: 500
    - family: Noto Sans
      fonts:
        - asset: assets/fonts/NotoSansRegular.ttf
          weight: 400
        - asset: assets/fonts/NotoSansMedium.ttf
          weight: 500