// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyB-V2_TQxUQBe6PIUrLH_jcRzgP0GNoVkQ',
    appId: '1:1009404413691:web:9e67f3b1299f5f1690d25e',
    messagingSenderId: '1009404413691',
    projectId: 'laflabemo',
    authDomain: 'laflabemo.firebaseapp.com',
    storageBucket: 'laflabemo.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDxvOnZDSFmFeyEo8bWBaQ4ZArcfufR1F8',
    appId: '1:1009404413691:android:f4f218619caba44d90d25e',
    messagingSenderId: '1009404413691',
    projectId: 'laflabemo',
    storageBucket: 'laflabemo.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDlkD2iGrLWrujApcamQlcYw-91XCkE4TQ',
    appId: '1:1009404413691:ios:adecf4a76449681190d25e',
    messagingSenderId: '1009404413691',
    projectId: 'laflabemo',
    storageBucket: 'laflabemo.appspot.com',
    iosBundleId: 'com.example.lafla',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDlkD2iGrLWrujApcamQlcYw-91XCkE4TQ',
    appId: '1:1009404413691:ios:61a7ebab2151626190d25e',
    messagingSenderId: '1009404413691',
    projectId: 'laflabemo',
    storageBucket: 'laflabemo.appspot.com',
    iosBundleId: 'com.example.lafla.RunnerTests',
  );
}
